### ISSUE TITLE
Notebook example using Bielik v2, vLLM, and Outlines for JSON output

### ISSUE THREAD

**Issue by TomekGancarczyk** [speakleash/Bielik-how-to-start#55]
Description:

I want to add a notebook example showing how to use Bielik v2 with vLLM and Outlines. This example will create a more production-ready solution that makes the model generate JSON output, controlled with Pydantic.

Goals:

	•	Show how to use Bielik v2, vLLM, and Outlines together.
	•	Make the model create structured JSON output.
	•	Use Pydantic to control and check the JSON output.
	•	Compare JSON output control without using Outlines and relaying on system prompt only

Deliverables:

	•	A Jupyter notebook (.ipynb) with the example.
	•	Clear code and comments.
	•	A sample JSON output.

Let me know if you have any suggestions or rules I should follow.

**Comment by IgorTest19** [comment]
Example implemented in the [PR#56](https://github.com/speakleash/Bielik-how-to-start/pull/56).
